const worldMainCities = [
    'New York',
    'Los Angeles',
    'Chicago',
    'Toronto',
    'Mexico City',
    'Vancouver',
    'Houston',
    'Miami',
    'Atlanta',
    'Montreal',
    'Washington DC',
    'San Francisco',
    'Seattle',
    'Boston',
    'Calgary',
    'Phoenix',
    'Dallas',
    'Denver',
    'Las Vegas',
    'Ottawa',
    'São Paulo',
    'Buenos Aires',
    'Rio de Janeiro',
    'Lima',
    'Bogotá',
    'Santiago',
    'Caracas',
    'Quito',
    'Montevideo',
    'La Paz',
    'Asunción',
    'Medellín',
    'Fortaleza',
    'Recife',
    'Salvador',
    'Brasília',
    'Porto Alegre',
    'Curitiba',
    'Belém',
    'Manaus',
    'Paris',
    'Londres',
    'Berlin',
    'Rome',
    'Madrid',
    'Barcelone',
    'Amsterdam',
    'Lisbonne',
    'Athènes',
    'Prague',
    'Budapest',
    'Munich',
    'Copenhague',
    'Stockholm',
    'Varsovie',
    'Dublin',
    'Zurich',
    'Bruxelles',
    'Oslo',
    'Helsinki',
    'Tokyo',
    'Pékin',
    'Shanghai',
    'Delhi',
    'Singapour',
    'Mumbai',
    'Séoul',
    'Manille',
    'Jakarta',
    'Bangkok',
    'Hanoï',
    'Ho Chi Minh Ville',
    'Kuala Lumpur',
    'Dacca',
    'Taipei',
    'Karachi',
    'Chennai',
    'Istanbul',
    'Jérusalem',
    'Abou Dabi',
    'Le Caire',
    'Lagos',
    'Johannesburg',
    'Nairobi',
    'Casablanca',
    'Tunis',
    'Dakar',
    'Accra',
    'Lubumbashi',
    'Maputo',
    'Addis-Abeba',
    'Abidjan',
    'Dar es Salaam',
    'Kampala',
    'Luanda',
    'Kigali',
    'Yaoundé',
    'Harare',
    'Bamako',
    'Conakry',
  ];

export default worldMainCities;